### ISSUE TITLE
Allow posting publicly

### ISSUE THREAD

**Issue by nicobao** [zkorum/zkorum#22]
Instead of only being able to post anonymously, we could allow for posting publicly too.
This feature was requested by some users.

# General requirements

- [ ] create a public profile associated with the existing user account (secured via DID and UCAN)
    - [ ] add profile picture
    - [ ] show communities in which they belong (based on email address verification or blockchain address verification or external credentials they registered). Maybe enable hiding certain info depending on use-case.
    - [ ] show public groups in which they belong (if the functionality exists)
    - [ ] hide private groups in which they belong (if the functionality exists) 
    - [ ] add general information
    - [ ] add work info
    - [ ] add studies info
    - [ ] add a functionality to import info from LinkedIn 
- [ ] allow the user account to post publicly
- [ ] allow anyone to follow public profiles

# AT Protocol compatibility
- [ ] make public profile compatible with AT Protocol (Bluesky)
