### ISSUE TITLE
Decentralized / Verifiable moderation

### ISSUE THREAD

**Issue by nicobao** [zkorum/zkorum#24]
Moderation rules are carefully chosen by ZKorum leadership to create a safe and inclusive space, yet encourage free speech.
Thought this process is not decentralized, ZKorum listens to its community opinion on the rules.
ZKorum implements the concept of Verifiable Moderation to ensure auditability of the moderation decision: watchdogs can verify is ZKorum is compliant with its own moderation policy.

# Core features

- [ ] Broadcast presentations in Nostr in the backend side
- [ ] Check whether presentation has been broadcast on the frontend side
- [ ] Allow anyone to flag content for moderation
- [ ] Create a set of common rules that everyone must abide to
- [ ] Create a set of rules on how moderators should behave. ZKorum team can dismiss a mod if the mod doesn't respect these rules.
- [ ] Organize how moderators are chosen and which scope they are given: mods (= public profile) are elected for each topic / community / language
- [ ] Create transparent moderation pages
    - [ ] Search posts by CID
    - [ ] Show CID that were flagged  
    - [ ] Create a process of review until the flagged post is eventually hidden from the main app (ex of potential statuses: not-flagged, flagged, under-review, non-compliant, compliant)
    - [ ] Allow anyone to post (publicly or not) to discuss whether the specific post should be hidden or not
    - [ ] Only a moderator can make the decision. The moderator must explain the decision-making.
    - [ ] The decision can be contested if enough users downvote it.
    - [ ] In that case a vote is cast automatically, and all moderators must vote (anonymously) to hide or not the post. Mods must explain their reasoning anonymously on top of the vote.
    - [ ] The result of the vote is a final decision. If the vote doens't reach majority, the original decision of the mod remains. No recourse is possible.

# Incentive for watchdogs

- [ ] Create a smart contract on the Filecoin blockchain to reward watchdogs that would automatically save the presentations broadcast to Nostr on FIlecoin, and then continuously check whether the data is hidden or not from ZKorum, and if yes, verify if there is a justified moderation decision.
- [ ] Allow users to pay these watchdogs via the smart contract.
