### ISSUE TITLE
[Meta] Project roadmap after first MVP 

### ISSUE THREAD

**Issue by nicobao** [zkorum/zkorum#42]
# Context

ZKorum MVP at ESSEC was full of learnings.

We pivot from ZKorum the social network to ZKorum the open-source social protocol R&D company, and separate social apps with distinct marketing, Afterwork and Agora.

# Focus

Within the next 9 months:
- ZKorum: reposition brand identity and marketing to an R&D lab working on designing cutting-edge open-source social protocols & implement Verifiable Moderation:
    - [ ] https://github.com/zkorum/zkorum/issues/43
    - [ ] https://github.com/zkorum/zkorum/issues/44
    - [ ] https://github.com/zkorum/zkorum/issues/45
    - [ ] https://github.com/zkorum/zkorum/issues/46
    - [ ] https://github.com/zkorum/zkorum/issues/47
- Afterwork: develop a more advanced product from the learning of ZKorum to acquire more users from universities and companies and hint towards monetization within the next 9 months
    - [x] https://github.com/zkorum/zkorum/issues/48
    - [x] https://github.com/zkorum/zkorum/issues/49
    - [x] https://github.com/zkorum/zkorum/issues/50
    - [x] https://github.com/zkorum/zkorum/issues/51
    - [x] https://github.com/zkorum/zkorum/issues/10
    - [x] https://github.com/zkorum/zkorum/issues/52 
    - [x] https://github.com/zkorum/zkorum/issues/53
    - [x] https://github.com/zkorum/zkorum/issues/54
- Agora: R&D with Proof of Passport and marketing to raise awareness and create hype
    - [x] https://github.com/zkorum/zkorum/issues/55
    - [ ] https://github.com/zkorum/zkorum/issues/56
    - [ ] https://github.com/zkorum/zkorum/issues/57
    - [ ] https://github.com/zkorum/zkorum/issues/58
    - [ ] https://github.com/zkorum/zkorum/issues/59
